apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: backend-secret
  namespace: amazon

spec:
  refreshInterval: 30m

  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: backend-secret

  data:

    - secretKey: PORT
      remoteRef:
        key: dev/amazon-clone/backend
        property: PORT

    - secretKey: MONGODB_URI
      remoteRef:
        key: dev/amazon-clone/backend
        property: MONGODB_URI

    - secretKey: JWT_SECRET
      remoteRef:
        key: dev/amazon-clone/backend
        property: JWT_SECRET

    - secretKey: NODE_ENV
      remoteRef:
        key: dev/amazon-clone/backend
        property: NODE_ENV

    - secretKey: LOG_LEVEL
      remoteRef:
        key: dev/amazon-clone/backend
        property: LOG_LEVEL