apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: ecommerce-hpa
  namespace: amazon-clone

spec:

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ecommerce

  minReplicas: 3

  maxReplicas: 10

  metrics:

  - type: Resource

    resource:

      name: cpu

      target:

        type: Utilization

        averageUtilization: 70