apiVersion: external-secrets.io/v1beta1

kind: SecretStore

metadata:

  name: aws-secret-store

  namespace: ecommerce

spec:

  provider:

    aws:

      service: SecretsManager

      region: ap-south-1

      auth:

        jwt:

          serviceAccountRef:

            name: external-secrets-sa