apiVersion: v1
kind: ServiceAccount

metadata:

  name: external-secrets-sa

  namespace: ecommerce

  annotations:

    eks.amazonaws.com/role-arn: arn:aws:iam::781195020338:role/external-secret-role